apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-dev-project
  namespace: argo-cd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: ns-1
  project: dev-project
  source:
    repoURL: https://github.com/mabusaa/argocd-example-apps
    path: guestbook
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
