apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev-project
  namespace: argo-cd
spec:
  description: "Allow all sources repo, allow local cluster and namespace ns-1 only as dest, allow all cluster and namespace scoped resources" 
  sourceRepos:
    - '*'
  destinations:
    - namespace: ns-1
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
