apiVersion: v1
kind: Secret
metadata:
  namespace: argo-cd
  labels:
    argocd-argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name:
  server: <api-serverURL>
  config: |
  {
    "bearerToken":
    "tlsClientConfig": {
      "insecure":
      "caData":
    }
  }
